Added news controller and `/personalized` route for fetching personalized news
StartSteps-Digital-Education-GmbH/News-App pull request #9
Opened 2024-12-04 10:01 UTC by bojana-petroska

This PR adds a new `/personalized` route to fetch news based on user preferences. The route uses `auth` middleware and accepts categories (required) and limit (optional, default: 10) as query parameters.

**Key changes:**

- Added `/personalized` route in the router.
- Implemented `getPersonalizedNews` to validate input, fetch news from NewsAPI, and format the response.
Included error handling for missing parameters `400` and server errors `500`.

2024-12-05 10:19 UTC, ahzia requested changes
Good Job @bojana-petroska 
Take a look at my inline comments, and add validation.

2024-12-05 10:19 UTC, ahzia commented on src/modules/News/controller.ts
> +  const { categories, limit = 10 } = req.query;
assign the default value in the validation schema

2024-12-05 10:19 UTC, ahzia commented on src/modules/News/controller.ts
> +  }
this will be done during the validation middleware

2024-12-05 10:19 UTC, ahzia commented on src/modules/News/controller.ts
> +    const formattedResponse = news.articles.map((article: any) => ({
Suggestion: add a type for `article `

2024-12-05 10:19 UTC, ahzia commented on src/modules/News/routes.ts
> +router.get('/personalized', auth, newsController.getPersonalizedNews);
Use validation middleware and validate queries.

2024-12-05 15:33 UTC, closed without merging

2024-12-06 13:55 UTC, bojana-petroska commented
This pull request was closed and the new one is: [new pull request](https://github.com/StartSteps-Digital-Education-GmbH/News-App/pull/14)